trigger:
- develop
- main
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

jobs:
# Build
- job: Build
  pool:
    vmImage: 'windows-2022'
  steps:
  # .NET 5 required for GitVersion
  - task: UseDotNet@2
    inputs:
      version: '5.x'
    displayName: 'Install .NET 5'
  - task: UseDotNet@2
    inputs:
      version: '6.x'
    displayName: 'Install .NET 6'
  - task: UseDotNet@2
    inputs:
      version: '7.x'
    displayName: 'Install .NET 7'
  - powershell: ./build.ps1
    displayName: 'Build'
  - publish: $(Build.SourcesDirectory)/BuildArtifacts/Packages/NuGet
    artifact: NuGet Package
    displayName: 'Publish NuGet packages as build artifact'
# Integration Tests Frosting Windows (.NET 6)
- job: Test_Frosting_Windows_Net6
  displayName: Integration Tests Frosting Windows (.NET 6)
  dependsOn: Build
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '6.x'
    displayName: 'Install .NET 6'
  - download: current
    artifact: NuGet Package
    displayName: 'Download build artifact'
  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Pipeline.Workspace)/NuGet Package
      targetFolder: $(Build.SourcesDirectory)/BuildArtifacts/Packages/NuGet
    displayName: 'Copy build artifact for test run'
  - powershell: ./build.ps1 --verbosity=diagnostic
    workingDirectory: ./tests/frosting/net6.0
    displayName: 'Run integration tests'
# Integration Tests Script Runner Windows (.NET tool)
- job: Test_Script_Runner_Windows_DotNetTool
  displayName: Integration Tests Script Runner Windows (.NET tool)
  dependsOn: Build
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '6.x'
    displayName: 'Install .NET 6'
  - download: current
    artifact: NuGet Package
    displayName: 'Download build artifact'
  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Pipeline.Workspace)/NuGet Package
      targetFolder: $(Build.SourcesDirectory)/BuildArtifacts/Packages/NuGet
    displayName: 'Copy build artifact for test run'
  - powershell: ./build.ps1 --verbosity=diagnostic
    workingDirectory: ./tests/script-runner
    displayName: 'Run integration tests'
